title: Glazewski Movie Reviews
author: Christian Glazewski
email: glazewskic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to a blog that showcases Christian Glazewski's opinions and thoughts on recent movies he's seen. Enjoy.
theme: minima

# social links
twitter_username: cdotglazewski # DO NOT include the @ character, or else the build will fail!
github_username:  cdotglazewski # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
